### ISSUE TITLE
Can't test latest release on Maven Central

### ISSUE THREAD

**Issue by FlorianKirmaier** [dustinkredmond/FXTrayIcon#93]
Based on the commits, i can see there should be a release after 4.2.0. Probably 4.2.1.

But i can't see the new version on MavenCentral.
Probably, something wen't wrong during the release process.

MavenCentral: https://mvnrepository.com/artifact/com.dustinredmond.fxtrayicon/FXTrayIcon
Release commit: https://github.com/dustinkredmond/FXTrayIcon/commit/c2e687f48fc891adf4e10b41e759a3addeb0c3e1

Can you release a new version? Maybe based on the latest commit.
Thank you!

**Comment by dustinkredmond** [comment]
I could have sworn I deployed the latest to Maven Central. Evidently, not. I'll get the latest pushed now. Thanks for bringing this up!

**Comment by dustinkredmond** [comment]
Sorry for the delay, had to move to newer Maven Central repository vs OSSRH which goes EOL at the end of this month. I just deployed 4.2.3 of FXTrayIcon there.

![Image](https://github.com/user-attachments/assets/35880c6e-e6a0-4aad-8764-1b5a98a1231d)

**Comment by ctoabidmaqbool** [comment]
At **mavenrepository** e.g. https://mvnrepository.com/artifact/com.dustinredmond.fxtrayicon/FXTrayIcon, it's still showing latest version `4.2.2` or is somethigs I 'am missing?

![Image](https://github.com/user-attachments/assets/f29d1b27-ad95-4e27-a6d1-419a87b7d011)
